version: '3.9'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=shelter
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "shelter.app:create_app()"
    environment:
      PYTHONUNBUFFERED: 'true'
      APP_SECRET: 'shelter_shelter'
    volumes:
      - '.:/shelter'
    ports:
      - '8000:8000'